---
#########################################################
## Set action                                          ##
#########################################################
# If action variable is not defined, gather status of the service
# If service not installed, set action to install.
# If the service is not started, set action to start.

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Podman is installed
- name: Podman is detected...
  when: '"podman" in ansible_facts.packages'
  block:
    # List containers from podman
    - name: Gather containers from podman...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: get_containers
        container_name: "{{ adguard_home_vars.container.name }}"
        result_var: result_get_containers

    # Default to install if container is absent; otherwise do not override action
    - name: Set action to install when container is absent
      ansible.builtin.set_fact:
        action: install
      when: result_get_containers is defined and ( result_get_containers | string is not search(adguard_home_vars.container.name) )
