---
#########################################################
## Uninstall action                                    ##
#########################################################
# Uninstall action
# variables:
#   - keep_data: true/false. Keep data when uninstalling. Default false.

#########################################################
## Uninstall configuration                             ##
#########################################################

# Set keep_data if not defined
- name: Set keep_data if not defined
  ansible.builtin.set_fact:
    keep_data: false
  when: keep_data is not defined

#########################################################
## Uninstall via podman                                ##
#########################################################

- name: Uninstall on podman ({{ adguard_home_vars.container.name }})
  when: adguard_home_vars.container.platform == "podman"
  block:
    # List containers from podman
    - name: Gather containers from podman...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: get_containers
        container_name: "{{ adguard_home_vars.container.name }}"
        result_var: result_get_containers

    # Remove container
    - name: Remove container {{ adguard_home_vars.container.name }}
      ansible.builtin.include_role:
        name: podman
      vars:
        action: delete_container
        container_name: "{{ adguard_home_vars.container.name }}"
        result_var: result_delete_container
      when: result_get_containers is defined and ( result_get_containers | string is search(adguard_home_vars.container.name) )

# Check result TODO

#########################################################
## Uninstall data                                      ##
#########################################################

# Start destroy_volumes from podman role
- name: Destroy container data folders for {{ adguard_home_vars.container.name }}...
  become: true
  ansible.builtin.include_role:
    name: podman
  vars:
    action: destroy_volumes
    container_volumes: "{{ adguard_home_vars.container.volumes }}"
  when:
    - adguard_home_vars.container.platform == "podman"
    - not (keep_data | bool)

#########################################################
## Post-uninstall                                      ##
#########################################################

# Unset variables
- name: Unset variables
  ansible.builtin.set_fact:
    keep_data:
